config/routes.rb
Locationapp::Application.routes.draw do

 
  resources :locations do
    resources :friends
  end

  root :to => 'Locations#index'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
	belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
	attr_accessible :name, :description, :created_at
	validates :name,	:presence => true,:length => {:maximum => 15 }
	validates :description, :presence => true

  has_many :friends

	def days_since_created
		(DateTime.now - created_at.to_datetime).to_i
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    location = Location.find(params[:location_id])
    @friends = location.friends.all
  end

  def new
    @location = Location.find(params[:location_id])
    @friend = @location.friends.new
  end

  def create
  end

  def show
  end

  def update
  end

  def destroy
  end

  def edit
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations=Location.all
  end

  def show
    @location= Location.find(params[:id])
  end

  def edit
    @location=Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])

    if @location.update_attributes(params[:location])
    redirect_to locations_path
    else
      render 'new'
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_path
  end

  def new 
    @location=Location.new
  end

  def create
    @location = Location.new(params[:location])
    if @location.save
      redirect_to locations_path
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/friends/create.html.erb
<h1>Friends#create</h1>
<p>Find me in app/views/friends/create.html.erb</p>

app/views/friends/destroy.html.erb
<h1>Friends#destroy</h1>
<p>Find me in app/views/friends/destroy.html.erb</p>

app/views/friends/edit.html.erb
<h1>Friends#edit</h1>
<p>Find me in app/views/friends/edit.html.erb</p>

app/views/friends/index.html.erb
<h1>Friends#index</h1>

app/views/friends/new.html.erb
<%= form_for([@location,@location.friends.build]) do |f| %>
	<%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :nickname %>
  <%= f.text_field :nickname %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit "Done" %>
<% end %>

app/views/friends/show.html.erb
<h1>Friends#show</h1>
<p>Find me in app/views/friends/show.html.erb</p>

app/views/friends/update.html.erb
<h1>Friends#update</h1>
<p>Find me in app/views/friends/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Locationapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
<% if @location.errors.any? %>
<div id = "error_explanation">
  <ul>
  <% @location.errors.full_messages.each do |msg|%>
    <li><%= msg %> </li>

  <% end %>
  </ul>
</div>
<% end %>
  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div >
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/create.html.erb
<header>this is create page<header>

app/views/locations/destroy.html.erb
<h1>Locations#destroy</h1>
<p>Find me in app/views/locations/destroy.html.erb</p>

app/views/locations/edit.html.erb
	<h2> Edit Location</h2>


<%= render "form" %>

app/views/locations/index.html.erb
<header>
	<h1 style = "text-align:center"> TRAVEL BLOG</h1>
</header>
<body>
	<div id = "wrapper">
	<%= link_to("Add new location",new_location_path ) %>

<ul>
<% @locations.each do |l| %>
<li>
	<h3>
		<%= l.name %>
	</h3>
	<%= l.days_since_created %>	
	<p>
		<%= link_to("Show", location_path(l.id))%> | <%= link_to("Edit", edit_location_path(l.id))%> | <%= link_to("Delete",location_path(l.id),:method =>:delete, :confirm => "This location will be deleted, are you really really sure?")%> 
	</p>
</li>	
<% end %>
</ul>
</div>
</body>

app/views/locations/new.html.erb
<h1>Add a new location</h1>
<p></p>
<%= render "form" %>

<%= link_to "Back", :back %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>

<div id="showcontent">
	<p><%= @location.description%></p>
</div>
<section>
<h4>
  Companions on this trip    
</h4> 
<p><%= link_to "Add new companion", new_location_friend_path(@location.id) %></p>
</section>
<%= link_to "Back", :back%>

app/views/locations/update.html.erb
<h1>Locations update</h1>
<p>The page has beeng updated</p>